name: catchup
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #for integrating firebase
  firebase_core: ^3.9.0
  #for handling firebase authentication
  firebase_auth: ^5.3.4
  #for handling google sign in
  google_sign_in: ^6.2.2

  #For accessing cloud firestore database:
  cloud_firestore: ^5.6.0

  #for showing network image
  cached_network_image: ^3.4.1

  #for picker image_picker:
  image_picker: ^1.1.2

  #for accessign Firebase Storage (for uploading files)
  firebase_storage: ^12.4.2


  #for showing emoji
  emoji_picker_flutter: ^4.3.0

  firebase_messaging: ^15.2.4

  saver_gallery: ^4.0.1
#  gallery_saver_updated: ^3.0.0


  #for storing images
  cloudinary: ^1.2.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  file_picker: ^8.1.7
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  andrSoid: "ic_launcher"
  ios: true
  image_path: "images/VibeChat.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env
