// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQUthsIemeYUoyj9F1qO_40wxRLXBM-E',
    appId: '1:370922849602:android:f4fb8b8629cf3e6d5a74db',
    messagingSenderId: '370922849602',
    projectId: 'catchup-dd515',
    storageBucket: 'catchup-dd515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWl0nT3CGLxtECwxPpNb_cg3JHtiMS1Ok',
    appId: '1:370922849602:ios:e8ab19def26006f35a74db',
    messagingSenderId: '370922849602',
    projectId: 'catchup-dd515',
    storageBucket: 'catchup-dd515.firebasestorage.app',
    androidClientId: '370922849602-212lmh20on9k9gn6hvf0urj8ptu20o87.apps.googleusercontent.com',
    iosClientId: '370922849602-sv40rvs1phjemu9lj7jh2uq1hft6b91h.apps.googleusercontent.com',
    iosBundleId: 'com.example.catchup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWl0nT3CGLxtECwxPpNb_cg3JHtiMS1Ok',
    appId: '1:370922849602:ios:e8ab19def26006f35a74db',
    messagingSenderId: '370922849602',
    projectId: 'catchup-dd515',
    storageBucket: 'catchup-dd515.firebasestorage.app',
    androidClientId: '370922849602-212lmh20on9k9gn6hvf0urj8ptu20o87.apps.googleusercontent.com',
    iosClientId: '370922849602-sv40rvs1phjemu9lj7jh2uq1hft6b91h.apps.googleusercontent.com',
    iosBundleId: 'com.example.catchup',
  );

}